# Project ID from the Supabase dashboard
project_id = "fybgcaeoxptmmcwgslpl"

[functions]
[functions.analyze-rug]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.get-coin]
verify_jwt = false

[functions.add-coin]
verify_jwt = false

[functions.poll-new-coins]
verify_jwt = false