// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llpzapckraerrqwlkusv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxscHphcGNrcmFlcnJxd2xrdXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMzgyODQsImV4cCI6MjA0OTkxNDI4NH0.mtCPzU6VEi0m6Jl1hoOW88-BGEDpH7qIPQ-m10ySbK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);